import Link from "next/link";
import { ExternalLink, Github, Instagram, Mail, MessageCircle } from "lucide-react";
import { RaksHexLogo } from "@/components/common/RaksHexLogo";

const GITHUB_URL = "https://github.com/Akshu1245/Rakshex-complete-codebase";
const VSCODE_URL = "https://marketplace.visualstudio.com/items?itemName=rakshex.rakshex-vscode";
const INSTAGRAM_URL = "https://www.instagram.com/rakshex.in?igsi=YWlzcDg2ODcybmpz";
const REDDIT_URL = "https://www.reddit.com/u/RaksHex_in/s/8zzCSUdomW";

export function Footer() {
  return <footer className="border-t border-white/[0.08] bg-[#070A0F]/70 py-12"><div className="mx-auto grid max-w-[1280px] gap-10 px-5 sm:px-6 lg:grid-cols-[1.35fr_repeat(3,0.75fr)] xl:px-8">
    <div><Link href="/" className="inline-flex"><RaksHexLogo size={30} /></Link><p className="mt-4 max-w-sm text-sm leading-6 text-neutral-500">The AI Action Control Plane for teams that need to authorize consequential agent actions before execution and keep verifiable evidence afterward.</p><p className="mt-3 text-xs text-neutral-600">Private beta · Bengaluru, India</p><div className="mt-5 flex gap-2"><a href={GITHUB_URL} target="_blank" rel="noopener noreferrer" className="rounded-md border border-white/10 p-2 text-neutral-400"><Github className="h-4 w-4" /></a><a href={INSTAGRAM_URL} target="_blank" rel="noopener noreferrer" className="rounded-md border border-white/10 p-2 text-neutral-400"><Instagram className="h-4 w-4" /></a><a href={REDDIT_URL} target="_blank" rel="noopener noreferrer" className="rounded-md border border-white/10 p-2 text-neutral-400"><MessageCircle className="h-4 w-4" /></a></div></div>
    <div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-neutral-500">Product</p><div className="mt-4 flex flex-col gap-3 text-sm"><Link href="/overview" className="text-neutral-400 hover:text-white">Overview</Link><Link href="/demo" className="text-neutral-400 hover:text-white">Public demo</Link><Link href="/waitlist" className="text-neutral-400 hover:text-white">Private beta</Link><Link href="/changelog" className="text-neutral-400 hover:text-white">Changelog</Link></div></div>
    <div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-neutral-500">Developers</p><div className="mt-4 flex flex-col gap-3 text-sm"><Link href="/docs" className="text-neutral-400 hover:text-white">Documentation</Link><Link href="/blog" className="text-neutral-400 hover:text-white">Research notes</Link><a href={VSCODE_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-neutral-400">VS Code extension <ExternalLink className="h-3 w-3" /></a><a href={GITHUB_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-neutral-400">Source repository <ExternalLink className="h-3 w-3" /></a></div></div>
    <div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-neutral-500">Trust</p><div className="mt-4 flex flex-col gap-3 text-sm"><Link href="/trust" className="text-neutral-400 hover:text-white">Trust Center</Link><Link href="/privacy" className="text-neutral-400 hover:text-white">Privacy</Link><Link href="/terms" className="text-neutral-400 hover:text-white">Terms</Link><Link href="/legal/dpa" className="text-neutral-400 hover:text-white">DPA</Link><a href="mailto:rakshex@gmail.com" className="inline-flex items-center gap-1.5 text-neutral-400"><Mail className="h-3.5 w-3.5" /> Contact</a></div></div>
  </div></footer>;
}
