"""
DEVPULSE.md Generator — Creates per-project context files so new agents get zero-shot onboarding.
Equivalent to AGENTS.md but with DevPulse-specific routing, memory, and agent instructions.
"""
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path


DEVPULSE_TEMPLATE = """# DEVPULSE.md — Auto-generated project context for AI agents
# Generated: {generated_at}
# Project: {project_name}

## Quick Facts
- **Stack**: {stack}
- **Package Manager**: {package_manager}
- **Test Runner**: {test_runner}
- **Lint/Format**: {lint_formatter}
- **CI/CD**: {cicd}
- **Entry Point**: {entry_point}
- **Build Command**: {build_cmd}
- **Test Command**: {test_cmd}

## Agent Routing (for Hermes)
When Hermes routes tasks to this project, use these agent assignments:
{agent_routing_section}

## Protected Operations
These operations require human handoff approval:
- DB migrations to production
- Production deployment
- Package dependency changes
- Security rule weakening
- Payment/Stripe configuration

## Key Files
{key_files_section}

## Git Conventions
- Branch naming: {branch_convention}
- Commit style: {commit_style}

## Memory Hooks
- On code change: `codemem add decision "$SUMMARY" --tags "$FILES"`
- On session start: Read `.commandcode/memory/session_state.md`
- On session end: Save state to `.commandcode/memory/session_state.md`

## Available Pipelines
{pipelines_section}

## Agent Registry
28 DevPulse agents available. Knowledge graph: `agents/KNOWLEDGE_GRAPH.json`
Primary agents for this project:
{primary_agents}

---
*This file auto-generated by DevPulse. Update with `devpulse init` to refresh.*
"""


def detect_stack(project_root: Path) -> dict:
    pkg_json = project_root / "package.json"
    tsconfig = project_root / "tsconfig.json"
    cargo_toml = project_root / "Cargo.toml"
    pyproject = project_root / "pyproject.toml"
    go_mod = project_root / "go.mod"

    stack = []
    package_manager = "npm"
    test_runner = "unknown"
    lint_formatter = ""
    entry_point = "src/index.ts"
    build_cmd = "npm run build"
    test_cmd = "npm test"
    cicd = "unknown"

    if pkg_json.exists():
        try:
            pkg = json.loads(pkg_json.read_text())
            if "next" in pkg.get("dependencies", {}) or "next" in pkg.get("devDependencies", {}):
                stack.append("Next.js")
            if "react" in pkg.get("dependencies", {}) or "react" in pkg.get("devDependencies", {}):
                stack.append("React")
            if "express" in pkg.get("dependencies", {}) or "express" in pkg.get("devDependencies", {}):
                stack.append("Express")
            if "fastify" in pkg.get("dependencies", {}) or "fastify" in pkg.get("devDependencies", {}):
                stack.append("Fastify")
            if "drizzle-orm" in pkg.get("dependencies", {}) or "drizzle-orm" in pkg.get("devDependencies", {}):
                stack.append("DrizzleORM")
            if "prisma" in pkg.get("dependencies", {}) or "prisma" in pkg.get("devDependencies", {}):
                stack.append("Prisma")
            if "tailwindcss" in pkg.get("dependencies", {}) or "tailwindcss" in pkg.get("devDependencies", {}):
                stack.append("Tailwind")
            if "vite" in pkg.get("dependencies", {}) or "vite" in pkg.get("devDependencies", {}):
                stack.append("Vite")
            if TypeScript := tsconfig.exists():
                stack.append("TypeScript")
            if "vitest" in pkg.get("devDependencies", {}):
                test_runner = "Vitest"
                test_cmd = "npx vitest run"
            elif "jest" in pkg.get("devDependencies", {}):
                test_runner = "Jest"
                test_cmd = "npx jest"
            if "eslint" in pkg.get("devDependencies", {}):
                lint_formatter += "ESLint "
            if "prettier" in pkg.get("devDependencies", {}):
                lint_formatter += "Prettier"
            if pkg.get("scripts", {}).get("build"):
                build_cmd = "npm run build"

            if pkg.get("main"):
                entry_point = pkg["main"]

            # Detect package manager
            if (project_root / "pnpm-lock.yaml").exists():
                package_manager = "pnpm"
            elif (project_root / "yarn.lock").exists():
                package_manager = "yarn"
            elif (project_root / "bun.lockb").exists():
                package_manager = "bun"

        except Exception:
            pass

    if cargo_toml.exists():
        stack.append("Rust")
        package_manager = "cargo"
        test_runner = "cargo test"
        build_cmd = "cargo build --release"
        test_cmd = "cargo test"
        entry_point = "src/main.rs"
        lint_formatter = "rustfmt + clippy"

    if pyproject.exists():
        stack.append("Python")
        package_manager = "uv/pip"
        test_runner = "pytest"
        build_cmd = ""
        test_cmd = "pytest"
        lint_formatter = "ruff"
        entry_point = "src/__init__.py"

    if go_mod.exists():
        stack.append("Go")
        package_manager = "go mod"
        test_runner = "go test"
        build_cmd = "go build ./..."
        test_cmd = "go test ./..."
        lint_formatter = "gofmt + golangci-lint"
        entry_point = "main.go"

    if (project_root / ".github" / "workflows").exists():
        workflows = list((project_root / ".github" / "workflows").glob("*.yml"))
        cicd = f"GitHub Actions ({len(workflows)} workflow(s))"

    return {
        "stack": ", ".join(stack) if stack else "Node.js/TypeScript",
        "package_manager": package_manager,
        "test_runner": test_runner,
        "lint_formatter": lint_formatter,
        "entry_point": entry_point,
        "build_cmd": build_cmd,
        "test_cmd": test_cmd,
        "cicd": cicd,
    }


def detect_key_files(project_root: Path) -> list[str]:
    patterns = [
        "README.md", "package.json", "tsconfig.json", "Dockerfile",
        "docker-compose.yml", ".env.example", ".github/workflows/*.yml",
        "src/index.ts", "src/main.ts", "src/app.ts", "src/server.ts",
        "src/main.rs", "src/main.go", "src/__init__.py",
        "vite.config.ts", "next.config.*", "drizzle.config.ts",
        "vitest.config.ts", "playwright.config.ts",
    ]
    found = []
    for pattern in patterns:
        matches = list(project_root.glob(pattern))
        for m in matches:
            found.append(str(m.relative_to(project_root)))
    return found[:15]


def detect_agent_routing(project_root: Path) -> str:
    routes = {
        "server/": "DEV-BACKEND (07) — Backend logic, middleware, services",
        "frontend/": "DEV-FRONTEND (08) — UI components, pages, client state",
        "devpulse-frontend/": "DEV-FRONTEND (08) — UI components, pages, client state",
        "devpulse-vscode/": "DEV-VSCODE (09) — Extension, webviews",
        "drizzle/": "DEV-DATABASE (10) — Schema, migrations, queries",
        "src/api/": "DEV-API (11) — tRPC routers, contracts",
        "src/security/": "DEV-SECURITY (12) — Auth, CSP, injection prevention",
        "docker/": "DEV-DEVOPS (13) — Containers, pipelines, infra",
        "docs/": "DOCS-WRITER (16) — Documentation, guides",
        "tests/": "QA-TESTER (15) — Unit tests, integration tests",
        "e2e/": "QA-TESTER (15) — End-to-end tests",
        "scripts/": "PULSE-COMMAND (00) — Automation scripts",
        "shared/": "DEV-FULLSTACK (14) — Cross-cutting shared code",
    }
    lines = []
    for dir_pattern, agent in routes.items():
        if (project_root / dir_pattern).exists():
            lines.append(f"- `{dir_pattern}` → {agent}")
    return "\n".join(lines) if lines else "- Auto-route based on file extension and task pattern"


def get_pipelines_section() -> str:
    try:
        from hermes.skills.pipeline import list_pipelines
        pipelines = list_pipelines()
        lines = []
        for p in pipelines[:8]:
            lines.append(f"- **{p['name']}**: {' → '.join(p['steps'])} ({p['success_rate']:.0%} success)")
        return "\n".join(lines)
    except Exception:
        return "- `research_web` — Search → scrape → synthesize\n- `security_audit` — Dep scan → vuln check → report\n- `code_review_flow` — Lint → type check → tests → merge"


def get_primary_agents() -> str:
    return """- **PULSE-COMMAND (00)** — Master orchestrator, auto-discovers work
- **DEV-BACKEND (07)** — Server-side implementation
- **DEV-FRONTEND (08)** — Client-side implementation
- **DEV-DATABASE (10)** — Schema and migrations
- **DEV-SECURITY (12)** — Security hardening
- **QA-TESTER (15)** — Test coverage
- **REVIEWER (17)** — Code review"""


def generate_devpulse_md(project_root: Path | None = None) -> str:
    if project_root is None:
        project_root = Path.cwd()

    project_name = project_root.name
    info = detect_stack(project_root)
    key_files = detect_key_files(project_root)
    agent_routing = detect_agent_routing(project_root)
    pipelines = get_pipelines_section()
    primary = get_primary_agents()

    content = DEVPULSE_TEMPLATE.format(
        generated_at=datetime.now().isoformat(),
        project_name=project_name,
        stack=info["stack"],
        package_manager=info["package_manager"],
        test_runner=info["test_runner"],
        lint_formatter=info["lint_formatter"],
        cicd=info["cicd"],
        entry_point=info["entry_point"],
        build_cmd=info["build_cmd"],
        test_cmd=info["test_cmd"],
        agent_routing_section=agent_routing,
        key_files_section="\n".join(f"- `{f}`" for f in key_files),
        branch_convention="feature/NN-description",
        commit_style="conventional commits (feat:, fix:, chore:)",
        pipelines_section=pipelines,
        primary_agents=primary,
    )

    output_path = project_root / "DEVPULSE.md"
    output_path.write_text(content, encoding="utf-8")
    return str(output_path)


if __name__ == "__main__":
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
    path = generate_devpulse_md(root)
    print(f"DEVPULSE.md generated: {path}")
