"""
Hermes + DevPulse Integration Test
Runs a task through the agent loop, triggers auto-skill generation, and outputs the SKILL.md.
"""
import asyncio
import sys
from pathlib import Path

# Add parent to path for imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from hermes.agent_loop import HermesAgent, GatewayEvent, SKILLS_DIR, MEMORY_DB, HONCHO_DB


async def test_skill_generation():
    print("=" * 60)
    print("  HERMES + DEVPULSE -- Skill Generation Test")
    print("=" * 60)
    print()

    agent = HermesAgent()
    print(f"  Memory DB:   {MEMORY_DB}")
    print(f"  Honcho DB:   {HONCHO_DB}")
    print(f"  Skills dir:  {SKILLS_DIR}")
    print(f"  Profiles:    {len(agent.profiles)} agents loaded")
    print()

    # ── Test 1: Submit a novel task that should trigger skill generation ──
    tasks = [
        ("Search the web for latest TypeScript 5.8 features and summarize them", "RESEARCH-ORCHESTRATOR"),
        ("Implement a rate limiting middleware for Express.js with sliding window", "DEV-BACKEND"),
        ("Create automated unit tests for the auth service covering edge cases", "QA-TESTER"),
        ("Analyze competitor pricing for API observability tools and generate report", "COMPETITIVE-WATCH"),
    ]

    for i, (task, agent_target) in enumerate(tasks):
        print(f"[TEST {i+1}/{len(tasks)}] Task: {task[:80]}...")
        print(f"               Agent: {agent_target}")

        # Simulate the agent loop processing
        await agent.event_queue.put(GatewayEvent(
            source="cli",
            event_type="task",
            content=task,
            agent_target=agent_target,
        ))

        # Process one tick
        await agent._tick()

        # Check what pattern was detected
        pattern = agent.skill_gen.detect_pattern(task)
        print(f"               Pattern: {pattern or 'none'}")

        # Check if skill was generated
        skills = list(SKILLS_DIR.glob("*.py"))
        if skills:
            newest = max(skills, key=lambda p: p.stat().st_mtime)
            print(f"               Skill generated: {newest.name}")
        print()

    # ── Show generated skills ──
    skills = sorted(SKILLS_DIR.glob("*.py"), key=lambda p: p.stat().st_mtime, reverse=True)
    print("=" * 60)
    print(f"  GENERATED SKILLS: {len(skills)} total")
    print("=" * 60)
    print()

    for skill_file in skills:
        print(f"  [SKILL] {skill_file.name}")
        content = skill_file.read_text(encoding="utf-8")
        # Show first 40 lines, filtering unicode for Windows console
        lines = content.split("\n")[:40]
        for j, line in enumerate(lines):
            safe = line.encode("ascii", errors="replace").decode("ascii")
            print(f"     {safe}")
        if len(content.split("\n")) > 40:
            print(f"     ... ({len(content.split(chr(10))) - 40} more lines)")
        print()

    # ── Show memory state ──
    print("=" * 60)
    print("  MEMORY STATE (Last 5 entries)")
    print("=" * 60)
    rows = agent.memory.conn.execute(
        "SELECT key, value, category, importance FROM memories ORDER BY updated_at DESC LIMIT 5"
    ).fetchall()
    for row in rows:
        print(f"  [{row['category']}] {row['key']}: {row['value'][:100]}... (importance: {row['importance']})")

    # ── Show Honcho model ──
    print()
    print("=" * 60)
    print("  HONCHO USER MODEL")
    print("=" * 60)
    print(agent.honcho.get_context_prompt())

    # ── Show learning log ──
    print()
    print("=" * 60)
    print("  LEARNING LOG")
    print("=" * 60)
    logs = agent.memory.conn.execute(
        "SELECT pattern, observation, action_taken, recorded_at FROM learning_log ORDER BY recorded_at DESC LIMIT 5"
    ).fetchall()
    for log in logs:
        print(f"  [{log['recorded_at']}] {log['pattern']}: {log['observation'][:80]}")
        print(f"    -> {log['action_taken']}")

    agent.memory.close()
    agent.honcho.conn.close()

    print()
    print("=" * 60)
    print("  TEST COMPLETE — Hermes skill generation verified")
    print("=" * 60)

    # Save the first SKILL.md equivalent
    if skills:
        skill_md = f"""# Hermes Auto-Generated Skill: {skills[0].stem}

**Generated by**: Hermes Agent Loop (Sense → Think → Act)
**Pattern detected**: Auto-detected from task description
**Status**: Active

## Source Code
```python
{skills[0].read_text(encoding='utf-8')}
```

## Metadata
- File: `{skills[0]}`
- Created: Auto-generated during integration test
- Category: See skill registry in SQLite FTS5 memory
- Self-improving: Yes (usage tracking + success rate in skills_registry)

## How It Works
1. Agent loop receives task → detects pattern → checks if skill exists
2. If no matching skill → generates new Python skill via template
3. Registers in SQLite skills_registry with usage tracking
4. Skill auto-improves via success_rate tracking and Honcho preference learning

## How to Invoke
```
/hermes <agent> <task description>
# Example:
/hermes backend implement rate limiting middleware
/hermes security audit dependency vulnerabilities
```
"""
        skill_md_path = SKILLS_DIR / f"{skills[0].stem}.md"
        skill_md_path.write_text(skill_md, encoding="utf-8")
        print(f"\n  SKILL.md saved: {skill_md_path}")


if __name__ == "__main__":
    asyncio.run(test_skill_generation())
