/**
 * `rakshex init` — the 3-question workspace wizard.
 *
 * Asks: agent name → allowed actions (plain-language checkboxes) → spending
 * limit in ₹. Auto-generates everything else: workspace identity, permission
 * slip (never "delegated authority" in UX copy), agent key (never "capability
 * token"), policy, receipt signing keys, idempotency key (never asked).
 *
 * Writes to `~/.rakshex/workspaces/<slug>/`. Stdlib only.
 */
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { randomBytes, randomUUID } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { generateReceiptKeypair } from "./receipts.js";

export const RAKSHEX_HOME = join(homedir(), ".rakshex");
export const WORKSPACES_DIR = join(RAKSHEX_HOME, "workspaces");

/** Fixed, documented INR→USD rate used when compiling ₹ limits into policy rules. */
export const INR_PER_USD = 83;

const ACTION_CHOICES = [
  { n: 1, label: "read data", tools: ["data.read", "data.query"], decision: "allow" as const },
  { n: 2, label: "send email", tools: ["email.send"], decision: "require_approval" as const },
  { n: 3, label: "move money", tools: ["money.transfer", "financial.refund"], decision: "require_approval" as const },
  { n: 4, label: "change code", tools: ["code.write", "code.exec"], decision: "require_approval" as const },
] as const;

export interface InitAnswers {
  agentName: string;
  allowed: number[];
  spendingLimitInr: number;
}

export function slugify(name: string): string {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return slug || "agent";
}

/** Build the PolicyDocument the wizard's answers imply. Pure — tested. */
export function buildInitPolicy(answers: InitAnswers) {
  const limitUsd = Math.round((answers.spendingLimitInr / INR_PER_USD) * 100) / 100;
  const rules: Array<Record<string, unknown>> = [
    {
      ruleId: "spending-limit",
      name: `Deny anything over the ₹${answers.spendingLimitInr} spending limit`,
      priority: 10,
      conditions: { operator: "AND", rules: [{ field: "cost_usd", op: "gt", value: limitUsd }] },
      action: "deny",
    },
  ];
  let priority = 20;
  for (const choice of ACTION_CHOICES) {
    const checked = answers.allowed.includes(choice.n);
    rules.push({
      ruleId: `action-${choice.label.replace(/\s+/g, "-")}`,
      name: `${choice.label}: ${checked ? choice.decision.replace("_", " ") : "denied (not granted)"}`,
      priority,
      conditions: {
        operator: "AND",
        rules: [{ field: "tool_name", op: "in", value: [...choice.tools] }],
      },
      action: checked ? choice.decision : "deny",
    });
    priority += 10;
  }
  return {
    version: 1,
    name: `${answers.agentName} — RaksHex workspace policy`,
    description:
      `Generated by \`rakshex init\`. Spending limit ₹${answers.spendingLimitInr} ` +
      `(≈ $${limitUsd}). Anything not explicitly granted is denied.`,
    rules,
  };
}

export interface InitResult {
  workspaceDir: string;
  workspaceId: string;
  agentName: string;
  agentKey: string;
  spendingLimitInr: number;
  policyPath: string;
}

/** Write a secret file with owner-only permissions (0600 & ~umask). */
function writeSecret(path: string, content: string): void {
  writeFileSync(path, content, { mode: 0o600 });
}

export function initWorkspace(answers: InitAnswers): InitResult {
  const slug = slugify(answers.agentName);
  const workspaceId = `ws_${randomBytes(8).toString("hex")}`;
  const dir = join(WORKSPACES_DIR, slug);
  mkdirSync(dir, { recursive: true });

  const agentKey = `rk_${randomBytes(24).toString("hex")}`;
  const keypair = generateReceiptKeypair(`ws-${slug}-receipt-1`);
  const policy = buildInitPolicy(answers);
  const permissionSlip = {
    kind: "permission-slip",
    workspaceId,
    agentName: answers.agentName,
    allowedActions: ACTION_CHOICES.filter((c) => answers.allowed.includes(c.n)).map((c) => c.label),
    spendingLimitInr: answers.spendingLimitInr,
    issuedAt: new Date().toISOString(),
    // Generated, never asked — retries of the same action reuse one key.
    idempotencyKey: randomUUID(),
  };

  writeFileSync(join(dir, "workspace.json"), JSON.stringify({ workspaceId, agentName: answers.agentName, createdAt: new Date().toISOString(), mode: "local" }, null, 2));
  writeSecret(join(dir, "agent-key"), agentKey + "\n");
  writeFileSync(join(dir, "permission-slip.json"), JSON.stringify(permissionSlip, null, 2));
  writeFileSync(join(dir, "policy.json"), JSON.stringify(policy, null, 2));
  writeSecret(join(dir, "receipt-private.pem"), keypair.privateKeyPem);
  writeFileSync(join(dir, "receipt-public.pem"), keypair.publicKeyPem);

  return {
    workspaceDir: dir,
    workspaceId,
    agentName: answers.agentName,
    agentKey,
    spendingLimitInr: answers.spendingLimitInr,
    policyPath: join(dir, "policy.json"),
  };
}

async function ask(rl: ReturnType<typeof createInterface>, q: string): Promise<string> {
  const answer = await rl.question(q);
  return answer.trim();
}

export interface Asker {
  ask(q: string): Promise<string>;
  close(): void;
}

/**
 * Question-asker that works both interactively and with piped stdin.
 * readline/promises drops buffered input after the first question when stdin
 * is not a TTY, so for pipes we consume all lines up front instead.
 */
export async function createAsker(): Promise<Asker> {
  if (input.isTTY) {
    const rl = createInterface({ input, output });
    return { ask: (q) => ask(rl, q), close: () => rl.close() };
  }
  let data = "";
  for await (const chunk of input) data += chunk;
  const lines = data.split(/\r?\n/);
  let i = 0;
  return {
    ask: async (q: string) => {
      output.write(q + "\n");
      return (lines[i++] ?? "").trim();
    },
    close: () => {},
  };
}

export async function cmdInit(flags: Record<string, string | boolean>): Promise<number> {
  const json = flags.json === true || flags.json === "true";
  const asker = await createAsker();

  try {
    const cwdName = process.cwd().split("/").pop() || "agent";
    const nameRaw = await asker.ask(`Agent name? [${cwdName}] `);
    const agentName = nameRaw || cwdName;

    console.log("\nWhat should it be allowed to do? (plain language — pick numbers, e.g. 1,3)");
    for (const c of ACTION_CHOICES) console.log(`  ${c.n}. ${c.label}`);
    const pickedRaw = await asker.ask("Allowed actions? [1] ");
    const picked = (pickedRaw || "1").toLowerCase() === "all"
      ? [1, 2, 3, 4]
      : (pickedRaw || "1")
          .split(",")
          .map((s) => parseInt(s.trim(), 10))
          .filter((n) => n >= 1 && n <= 4);
    const allowed = [...new Set(picked)];

    const limitRaw = await asker.ask("Spending limit in ₹? [500] ");
    const spendingLimitInr = Math.max(1, parseInt(limitRaw || "500", 10) || 500);

    const result = initWorkspace({ agentName, allowed, spendingLimitInr });

    if (json) {
      console.log(JSON.stringify({ ok: true, ...result, agentKey: "***redacted***" }));
    } else {
      console.log(`
Workspace ready: ${result.workspaceDir}
  workspace id : ${result.workspaceId}
  agent key    : ${result.agentKey.slice(0, 11)}… (full key in agent-key file — keep it secret)
  permission slip, policy, and receipt keys generated automatically.

Next:
  rakshex local   start the firewall stack (Docker) against this workspace
  rakshex demo    watch a ₹10,000 refund get DENY'd in 60 seconds
`);
    }
    return 0;
  } finally {
    asker.close();
  }
}
