/**
 * `rakshex local` — one-command local stack (interim until the hosted
 * gateway exists).
 *
 * Generates `.env` secrets itself (POSTGRES_PASSWORD, JWT_SECRET — the two
 * values docker-compose.yml would otherwise leave on insecure dev defaults),
 * then runs `docker compose up -d` and waits for the API health check.
 * Kills onboarding steps 2–6 of the old 14-step flow.
 */
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { homedir } from "node:os";
import { randomBytes } from "node:crypto";
import { RAKSHEX_HOME } from "./init.js";

const LOCAL_DIR = join(RAKSHEX_HOME, "local");
const ENV_PATH = join(LOCAL_DIR, ".env");
const HEALTH_URL = "http://localhost:3000/api/health";

function findComposeFile(): string | null {
  let dir = process.cwd();
  for (let i = 0; i < 6; i++) {
    const candidate = join(dir, "docker-compose.yml");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

function docker(args: string[], cwd: string): { ok: boolean; out: string } {
  const r = spawnSync("docker", args, { cwd, encoding: "utf8" });
  const out = `${r.stdout ?? ""}${r.stderr ?? ""}`.trim();
  return { ok: r.status === 0, out };
}

function ensureEnv(): string {
  mkdirSync(LOCAL_DIR, { recursive: true });
  if (!existsSync(ENV_PATH)) {
    const lines = [
      "# Generated by `rakshex local` — do not commit. Regenerate with `rakshex local --reset`.",
      `POSTGRES_PASSWORD=${randomBytes(24).toString("hex")}`,
      `JWT_SECRET=${randomBytes(48).toString("hex")}`,
      "NODE_ENV=development",
    ];
    writeFileSync(ENV_PATH, lines.join("\n") + "\n", { mode: 0o600 });
    console.log(`Generated secrets: ${ENV_PATH}`);
  }
  return ENV_PATH;
}

async function waitForHealth(timeoutMs: number): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(HEALTH_URL);
      if (res.ok) return true;
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 3000));
  }
  return false;
}

export async function cmdLocal(
  positional: string[],
  flags: Record<string, string | boolean>,
): Promise<number> {
  const sub = positional[0] ?? "up";

  const hasDocker = docker(["--version"], process.cwd()).ok;
  if (!hasDocker) {
    console.error("rakshex local needs Docker. Install it from https://docs.docker.com/get-docker/ and retry.");
    return 2;
  }

  const compose = findComposeFile();
  if (!compose) {
    console.error("No docker-compose.yml found here or in parent dirs. Run `rakshex local` from your rakshex checkout.");
    return 2;
  }
  const root = dirname(compose);

  if (sub === "down") {
    const r = docker(["compose", "-f", compose, "down"], root);
    console.log(r.out || "Stack stopped.");
    return r.ok ? 0 : 2;
  }
  if (sub !== "up") {
    console.error(`Unknown subcommand: ${sub}. Usage: rakshex local [up|down] [--build] [--reset]`);
    return 2;
  }

  if (flags.reset === true && existsSync(ENV_PATH)) {
    const { unlinkSync } = await import("node:fs");
    unlinkSync(ENV_PATH);
  }
  const envFile = ensureEnv();

  const args = ["compose", "-f", compose, "--env-file", envFile, "up", "-d"];
  if (flags.build === true) args.push("--build");
  console.log("Starting RaksHex stack (postgres, redis, api, worker, web)…");
  const up = docker(args, root);
  if (!up.ok) {
    console.error(up.out || "docker compose up failed.");
    return 2;
  }

  console.log("Waiting for the API health check…");
  const healthy = await waitForHealth(180_000);
  if (!healthy) {
    console.error(`API did not become healthy at ${HEALTH_URL} within 3 minutes.`);
    console.error("Check `docker compose logs api` in the checkout for details.");
    return 2;
  }

  console.log(`
RaksHex is running locally:
  API        http://localhost:3000
  Dashboard  http://localhost:3001
  Health     ${HEALTH_URL}

Next:
  rakshex demo    watch a ₹10,000 refund get DENY'd in 60 seconds
  rakshex local down   stop everything
`);
  return 0;
}
